# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tmypackage\"\x1e\n\x0eMessageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2P\n\tMyService\x12\x43\n\nGetMessage\x12\x19.mypackage.MessageRequest\x1a\x1a.mypackage.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=28
  _globals['_MESSAGEREQUEST']._serialized_end=58
  _globals['_MESSAGERESPONSE']._serialized_start=60
  _globals['_MESSAGERESPONSE']._serialized_end=94
  _globals['_MYSERVICE']._serialized_start=96
  _globals['_MYSERVICE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
